//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public int IdEquipo { get; set; }
        public string Nombre { get; set; }
        public int NumeroPatrocinadores { get; set; }
        public int NumeroPilotos { get; set; }
        public Nullable<int> IdPiloto { get; set; }
        public Nullable<decimal> Costo { get; set; }
    
        public virtual Piloto Piloto { get; set; }
    }
}
